### PR TITLE
Added Catch The Dot Game recipe

### PR DESCRIPTION
**Pull request by adamlubek**
This one is a little bit unusual :)

### CODE REVIEW

**Comment by btroncone** [comment]
Oh, this is awesome! Should have it merged quickly. 👍 

Also, what is the best way to contact you outside of GitHub? Want to bounce an idea off you :)

**Comment by adamlubek** [comment]
sweet!

email's the best: adamlubek@gmail.com

:)

**Comment by btroncone** [comment]
Thanks! Be in touch soon. 👍

**Comment by btroncone** [comment]
@adamlubek Looks like I jumped the gun a bit on email, still need to work out a few details but will be in touch soon. :)

Merging the PR 👍

**Comment by btroncone** [comment]
Oops! Unless I'm missing it, it looks like we are missing an update to the `SUMMARY.md` file to include the new recipe. This is what Gitbook uses to build the table of contents. Could you include the new recipe there as well, thanks!

**Comment by adamlubek** [comment]
I missed this one, sorry! changes pushed :)

no worries about email, I'm waiting patiently :)

**Comment by btroncone** [comment]
Merging 👍

**Comment by adamlubek** [comment]
sweeeet!

**Pull request merged**
