### PR TITLE
Added uncover image game recipe

### PR DESCRIPTION
**Pull request by adamlubek**

### CODE REVIEW

**Comment by btroncone** [comment]
Awesome man! Would you be able to add link in `Summary.md` file as well? That's what controls the ToC in gitbook. Thanks!

**Comment by adamlubek** [comment]
Silly me, I forgot it again lol 
done now :)

**Comment by btroncone** [comment]
Thanks, merging!

**Comment by adamlubek** [comment]
thanks! :)

**Comment by adamlubek** [comment]
hey, @btroncone , it looks like learnrxjs.io still doesn't include this recipe :(

**Comment by btroncone** [comment]
@adamlubek Yeah I'm having some issues. Gitbook is dropping support for legacy and their build process is currently failing. I'm in the process of updating to the new GitBook, but I'm being overly cautious as to not screw up any of the current URL's. Hopefully I'll have it all resolved within the week and can start pushing out new content again.

Sorry for the delay!

**Comment by adamlubek** [comment]
I see @btroncone ! let me know if I can help with anything :)

**Comment by btroncone** [comment]
@adamlubek Still working through some miscellaneous styling issues but the site is now updated with all the new content!

**Comment by adamlubek** [comment]
sweet @btroncone ! :)

**Pull request merged**
