### PR TITLE
Added space invaders recipe

### PR DESCRIPTION
**Pull request by adamlubek**
This one uses mostly functional programming/state management inside scan but RxJs drives it all so maybe it's good for LearnRxJs too :)

### CODE REVIEW

**Comment by btroncone** [comment]
This is awesome, thanks! 👍

**Comment by adamlubek** [comment]
sweeeett, thanks! :)

**Comment by btroncone** [comment]
@adamlubek Wanted to shout this out to you since you have been killing it with all these game examples. If you ever need an idea, here's a request! :)

https://twitter.com/mattpodwysocki/status/1101225329815764992

**Comment by adamlubek** [comment]
oooh, this is awesome game, thanks for an idea @btroncone , challenge accepted! :)

**Comment by btroncone** [comment]
Oh man, super excited to see this! Can’t wait! 👏👏

**Pull request merged**
