### PR TITLE
Added Stop Watch recipe

### PR DESCRIPTION
**Pull request by adamlubek**

### CODE REVIEW

**Comment by btroncone** [comment]
This is really great, I love the design and all the configuration options. 👍 

Small nitpick, do you think we should start the speed to 1000 rather than 500 by default?

**Comment by adamlubek** [comment]
coool! :)

good point, that's the changes pushed :)

**Comment by btroncone** [comment]
Merging! 👍

**Comment by adamlubek** [comment]
thanks :)

**Pull request merged**
