### PR TITLE
Added click ninja game recipe

### PR DESCRIPTION
**Pull request by adamlubek**

### CODE REVIEW

**Comment by btroncone** [comment]
@paschalidi I’m fine with these being together. Since this uses gitbook behind the scenes I’ve found it best to just include the recipe and table of contents (and relationship) updates together into one PR.

**Comment by btroncone** [comment]
No worries!

**Comment by btroncone** [comment]
Love this one @adamlubek, thanks!

**Comment by adamlubek** [comment]
thanks @btroncone , hope you're honing your ninja skills :D

thanks for review and kind words @paschalidi  :)

**Pull request merged**
